# Generated by Django 4.2.20 on 2025-05-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('bed_count', models.PositiveIntegerField()),
                ('facilities', models.TextField()),
                ('is_occupied', models.BooleanField(default=False)),
            ],
        ),
    ]
