# Generated by Django 4.2.20 on 2025-05-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='is_occupied',
            new_name='has_ac',
        ),
        migrations.RemoveField(
            model_name='room',
            name='facilities',
        ),
        migrations.AddField(
            model_name='room',
            name='has_attached_bathroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='room',
            name='bed_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
