# Generated by Django 4.2.20 on 2025-05-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='bed_count',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_available',
        ),
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
