# Generated by Django 4.2.21 on 2025-05-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_room_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='number_of_guests',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
