# Generated by Django 4.2.21 on 2025-05-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_reservation_number_of_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='number_of_guests',
        ),
        migrations.AddField(
            model_name='reservation',
            name='guests',
            field=models.ManyToManyField(to='rooms.guest'),
        ),
    ]
