# Generated by Django 4.2.21 on 2025-05-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_remove_reservation_guest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='allow_guest_overlap',
            field=models.BooleanField(default=False, help_text='Check this to allow the same guest to have overlapping reservations'),
        ),
    ]
