# Generated by Django 4.2.21 on 2025-05-16 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_reservation_allow_guest_overlap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['building', 'floor', 'number']},
        ),
        migrations.AddField(
            model_name='room',
            name='beds',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='chairs',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='room',
            name='donation_due',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Suggested donation amount for this room', max_digits=8),
        ),
        migrations.AddField(
            model_name='room',
            name='foldable_cots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='has_kitchen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='mats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='needs_repair',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='needs_supplies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='notes',
            field=models.TextField(blank=True, help_text='Special notes about this room', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='pillows',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='room',
            name='repair_notes',
            field=models.TextField(blank=True, help_text='Describe what repairs are needed', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('DORM', 'Dormitory'), ('PRIVATE', 'Private Room'), ('SUITE', 'Suite'), ('HALL', 'Hall')], default='PRIVATE', max_length=10),
        ),
        migrations.AddField(
            model_name='room',
            name='stools',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='supply_notes',
            field=models.TextField(blank=True, help_text='List of supplies needed', null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='rooms.building')),
            ],
            options={
                'ordering': ['building', 'number'],
                'unique_together': {('building', 'number')},
            },
        ),
        migrations.AddField(
            model_name='room',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.building'),
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.floor'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('building', 'floor', 'number')},
        ),
        migrations.RemoveField(
            model_name='room',
            name='price_per_night',
        ),
    ]
