# Generated by Django 4.2.21 on 2025-05-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_building_alter_room_options_room_beds_room_chairs_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['number', 'building', 'floor']},
        ),
        migrations.RemoveField(
            model_name='room',
            name='has_ac',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_available',
        ),
        migrations.AddField(
            model_name='room',
            name='has_fan',
            field=models.BooleanField(default=False, verbose_name='Has fan'),
        ),
        migrations.AlterField(
            model_name='room',
            name='donation_due',
            field=models.DecimalField(decimal_places=2, help_text='Suggested donation amount for this room', max_digits=8),
        ),
    ]
