# Generated by Django 4.2.21 on 2025-05-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_room_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='needs_cleaning',
            field=models.BooleanField(default=False),
        ),
    ]
