# Generated by Django 4.2.21 on 2025-06-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0013_room_needs_cleaning'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='building_type',
            field=models.CharField(choices=[('ROOMS', 'Rooms Only'), ('DORMS', 'Dormitories Only'), ('BOTH', 'Rooms & Dormitories')], default='BOTH', help_text='What types of accommodations this building has', max_length=10),
        ),
    ]
