# Generated by Django 4.2.21 on 2025-06-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0014_building_building_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['number', 'building', 'floor'], 'verbose_name_plural': 'Rooms and Dorms'},
        ),
        migrations.AddField(
            model_name='floor',
            name='allowed_room_types',
            field=models.JSONField(default=list, help_text="List of allowed room types for this floor (e.g. ['PRIVATE', 'DORM'])"),
        ),
    ]
