# Generated by Django 4.2.21 on 2025-09-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0015_alter_room_options_floor_allowed_room_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='building_type',
        ),
        migrations.AlterField(
            model_name='floor',
            name='allowed_room_types',
            field=models.JSONField(default=list, help_text='List of allowed room types for this floor'),
        ),
    ]
