# Generated by Django 4.2.21 on 2025-09-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0016_remove_building_building_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='allowed_room_types',
            field=models.JSONField(default=list, help_text='List of allowed room types for this floor (codes: PRIVATE, MALE_DORM, FEMALE_DORM)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('PRIVATE', 'Private room'), ('MALE_DORM', 'Male dormitory'), ('FEMALE_DORM', 'Female dormitory')], default='PRIVATE', max_length=12),
        ),
    ]
