# Generated by Django 4.2.21 on 2025-10-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0018_map_old_room_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='guest_photos/'),
        ),
    ]
