# Generated by Django 4.2.21 on 2025-10-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0019_guest_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='passport_scan',
            field=models.ImageField(blank=True, null=True, upload_to='guest_passports/'),
        ),
        migrations.AddField(
            model_name='guest',
            name='visa_scan',
            field=models.ImageField(blank=True, null=True, upload_to='guest_visas/'),
        ),
    ]
